version: "3"
services:
  canales:
    build: ./canales
    ports:
      - "5002:5000"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db

  monitor:
    build: ./monitor
    ports:
      - "5001:5000"
    depends_on:
      - canales
    networks:
      - app-network

  streamlit-app:
    build: ./monitor_front
    ports:
      - "8501:8501"
    depends_on:
      - canales
      - monitor
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge