version: "3"
services:
  canales:
    build: ./canales
    ports:
      - "5002:5000"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HASH_SECRET_KEY=4f3e8f3b6f4d2e8f90baf8d0ec8b6c4b
    networks:
      - app-network
    depends_on:
      - postgres_db

  monitor:
    build: ./monitor
    ports:
      - "5001:5000"
    depends_on:
      - canales
    networks:
      - app-network

  streamlit-app:
    build: ./monitor_front
    ports:
      - "8501:8501"
    depends_on:
      - canales
      - monitor
    networks:
      - app-network
    
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge